### ISSUE TITLE
Disable Recaptcha

### ISSUE THREAD

**Issue by nausikaa-dot** [someone-stole-my-name/gShort#6]
Is there any way to disable recaptcha completely? It's an important privacy feature to me.

**Comment by nausikaa-dot** [comment]
Okay, after creating this issue I started digging through the code:

```
        {{- if .ReCaptcha.SiteKey }}
            <script type="text/javascript"
                    src="https://www.google.com/recaptcha/api.js?render={{ .ReCaptcha.SiteKey }}"></script>
        {{- end }}
```

Is an empty value falsey here? Meaning it won't be rendered?

**Comment by someone-stole-my-name** [comment]
Hello,

You are correct, leave both `SiteKey` and `SecretKey` as empty strings to disable reCaptcha support.

**Comment by someone-stole-my-name** [comment]
Make sure you have 5112d4032613a362d69fd8eaede330572114ce9a, there was a bug in the website. It should work as expected now.

**Comment by nausikaa-dot** [comment]
Thanks! It might be worth mentioning in the README.
